### ISSUE TITLE
úprava medailonku - Kos

### ISSUE THREAD

**Issue by KosakL** [pirati-web/praha11.pirati.cz#1]
Prosím, upravit text, resp. jeho strukturu.
"Chci se věnovat třem oblastem:
  - Řešení dopravy....
  - Transparentní radnici...
  - Rozvoji Prahy 11.... "

Aby ten text nebyl v jednom odstavci, ale ty tři oblasti byli v odrážkách. Ono se to blbě čte takto dohromady. 

Díky, L.

**Comment by JanSuchanek** [comment]
Updated
